Update JsonSingleFileDownload.yml

diff --git a/.github/workflows/JsonSingleFileDownload.yml b/.github/workflows/JsonSingleFileDownload.yml
--- a/.github/workflows/JsonSingleFileDownload.yml
+++ b/.github/workflows/JsonSingleFileDownload.yml
@@ -35,6 +35,9 @@ jobs:
         run: |
          if [[ "${{ inputs.environment }}" == "dev" || ( "${{ inputs.environment }}" == "Prod" && "${{ inputs.code-repository }}" == "mspriya92/ProjectTest" ) ]]; then
            echo "Successfully logged in"
+         else
+           echo "Error"
+           exit 1
          fi
            
       - name: Download and update nsi.json with secrets
